### ISSUE TITLE
[Error?/Feature Request] Link Item and Resource DnD5e Compatibility

### ISSUE THREAD

**Issue by Foundry37** [jessev14/dnd5e-character-monitor#12]
Hello there, love the mod.

I've found that when resource changes are automated instead of manually done by the player it doesn't always recognise things like spell slot changes or equipping/unequipping.

Similarly the mod "Link Item and Resource DnD5e" provides a resource override to set ammo quantity or feature uses as a resource that depletes on its own as you use them up. It doesn't seem to register those resources changing at all whether done manually or automatically?

Might just be me in which case I'll live, but if not I'd appreciate some advice on where they might be clashing to fix myself if you don't want to do a compatibility fix.

**Comment by jessev14** [comment]
So the module was always designed to just track manual changes. There may be some automatic changes that are tracked, but that's actually not intentional.

I'm not familiar with how "Link Item and Resource DnD5e" works, but I would say if you're running automation this way, then you could probably manually create the monitor messages using ItemMacro.

The chat message styling is pretty much all CSS, so as long as you create the chat message with the proper classes (and flags maybe), you should be able to recreate the monitor messages.
