### ISSUE TITLE
[Feature] Different shat card colors for different currency. 

### ISSUE THREAD

**Issue by Orionox** [jessev14/dnd5e-character-monitor#13]
Having a different chat color for different currencies would just help GM's see whats happening better at a glace.

**Comment by jessev14** [comment]
Doable, but would take a bit of work.

This module was funded by a commission, and unfortunately I don't have the means to develop modules in my free time.
If you'd like to implement it yourself I'd be happy to merge a pull request. Otherwise, if you'd like to fund this feature, you can reach out to me on Discord: `enso#0361`.
